version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_revolver_solutions
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - revolver-solutions:/var/lib/mysql

volumes:
  revolver-solutions: