GET http://localhost:80/api/item?id=99
Accept: application/json

###
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "Yassine",
  "lastName": "chalh",
  "username": "yaashaall",
  "email": "yassinechalh10@gmail.com",
  "password": "passe12passe"
}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "yaashall",
  "password": "passe12passe"
}


###

GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ5YWFzaGFhbGwiLCJyb2xlIjoiVFJBSU5FRSIsImVtYWlsIjoieWFzc2luZWNoYWxoMTBAZ21haWwuY29tIiwiaWF0IjoxNzE4MDQ3MjkwLCJleHAiOjE3MTgxMzM2OTB9.hLxB6YMOGpg8LwWCAKmfOYhBJUXiAHqDwMdVlPP5MJKmzf_6_64UPO8yxa_fzVjh



###

POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ5YWFzaGFsbCIsImlhdCI6MTcxNjIzMzc3MywiZXhwIjoxNzE2MzIwMTczfQ.IBNVVprP4wmKoQb6VRjMWGrpFttluq5B7_uGrlUU34_iL08i5FTt6OOG89bZG9EX

###

GET http://localhost:8080/api/v1/user/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ5YWFzaGFhbGwiLCJyb2xlIjoiVFJBSU5FRSIsImVtYWlsIjoieWFzc2luZWNoYWxoMTBAZ21haWwuY29tIiwiaWF0IjoxNzE4MDQ3MjkwLCJleHAiOjE3MTgxMzM2OTB9.hLxB6YMOGpg8LwWCAKmfOYhBJUXiAHqDwMdVlPP5MJKmzf_6_64UPO8yxa_fzVjh



###
GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ5YWFzaGFsbCIsInJvbGUiOiJBRE1JTiIsImVtYWlsIjoieWFzc2luZWNoYWxoOUBnbWFpbC5jb20iLCJpYXQiOjE3MTg1NDk4NTUsImV4cCI6MTcxODYzNjI1NX0._n-0iw7eOhAEm-e3n3hib9SGK46CFrBYEgscHNPQBzePGLdtFX4dyac3RKryvvGI


###
GET http://localhost:8080/api/v1/program
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ5YWFzaGFsbCIsInJvbGUiOiJBRE1JTiIsImVtYWlsIjoieWFzc2luZWNoYWxoOUBnbWFpbC5jb20iLCJpYXQiOjE3MTg1NDk4NTUsImV4cCI6MTcxODYzNjI1NX0._n-0iw7eOhAEm-e3n3hib9SGK46CFrBYEgscHNPQBzePGLdtFX4dyac3RKryvvGI



###
POST http://localhost:8080/api/v1/user/8c2b73b1-2bef-11ef-8de0-aec2f9ed894c/programs/8c41e96b-2bef-11ef-8de0-aec2f9ed894c/enroll
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ5YWFzaGFsbCIsInJvbGUiOiJBRE1JTiIsImVtYWlsIjoieWFzc2luZWNoYWxoOUBnbWFpbC5jb20iLCJpYXQiOjE3MTg1NDk4NTUsImV4cCI6MTcxODYzNjI1NX0._n-0iw7eOhAEm-e3n3hib9SGK46CFrBYEgscHNPQBzePGLdtFX4dyac3RKryvvGI

