#DATASOURCE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/trainingapp_db_dev?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA CONFIG
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.hibernate=ERROR
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

spring.sql.init.mode=always
spring.sql.init.platform=mysql

imgur.clientId=c524c60bca7311a
imgur.url=https://api.imgur.com/3/image

#google.drive.application.name=AppTraining
#google.drive.credentials=credentials.json

#logging.level.root=DEBUG
#logging.level.com.revolversolutions.trainingmanagement=DEBUG

